FilesS3Bucket:
  Type: "AWS::S3::Bucket"
  Properties:
    BucketName: !Sub "${Environment}-${ProjectName}-files"
S3Bucket:
  Type: "AWS::S3::Bucket"
  Properties:
    BucketName: !Sub "${Environment}-${ProjectName}-${AppName}"
