INSERT INTO pet_species (id, name, order_number)
VALUES
    (1, 'Hund', 1),
    (3, 'Katze', 2),
    (5, 'Kleintier', 3),
    (4, 'Vogel', 4),
    (6, 'Terrarientier', 5),
    (2, 'Pferd', 6);

INSERT INTO pet_breeds (id, name)
VALUES (1, 'Weißer Schäferhund'),
       (2, 'Bulldogge'),
       (3, 'Französische Bulldogge'),
       (4, 'Europäisch Kurzhaar'),
       (5, 'Mischling (Hund)'),
       (6, 'Schäferhund × Labrador (Mischling)'),
       (7, 'Deutscher Schäferhund'),
       (8, 'Rottweiler'),
       (9, 'Staffordshire Bullterrier'),
       (10, 'Shih Tzu'),
       (11, 'Cavalier King Charles Spaniel'),
       (12, 'Cavalier King Charles × Toypudel (Mischling)'),
       (13, 'Herdenschutzhund'),
       (14, 'Wachtel'),
       (15, 'Huhn'),
       (16, 'Schildsittich'),
       (17, 'Gelbwangensittich'),
       (18, 'Deutscher Riese (Kaninchen)'),
       (19, 'Blauer Wiener (Kaninchen)'),
       (20, 'Labrador Retriever'),
       (21, 'Chihuahua'),
       (22, 'Podenco (Mischling)'),
       (23, 'Britisch Kurzhaar'),
       (24, 'Scottish Fold'),
       (25, 'Pitbull'),
       (26, 'Kangal'),
       (27, 'Boxer'),
       (28, 'Old English Bulldogge'),
       (29, 'Jack Russell Terrier'),
       (30, 'Cane Corso'),
       (31, 'Malinois'),
       (32, 'Ragdoll'),
       (33, 'Nymphensittich'),
       (34, 'Halsbandsittich'),
       (35, 'Seidenhuhn'),
       (36, 'Widder (Kaninchen)'),
       (37, 'Löwenkopf (Kaninchen)'),
       (38, 'Zwergkaninchen'),
       (39, 'Appenzeller × Labrador (Mischling)'),
       (40, 'Aussiedoodle (Mischling)'),
       (41, 'Beagle'),
       (42, 'Bolognese'),
       (43, 'Glatthaar-Meerschweinchen'),
       (44, 'Golden Retriever'),
       (45, 'Hauskaninchen'),
       (46, 'Hauskatze'),
       (47, 'Jagdterrier'),
       (48, 'Malinois × Schweizer Sennenhund (Mischling)'),
       (49, 'Malteser (Mischling)'),
       (50, 'Meerschweinchen'),
       (51, 'Mini Lop'),
       (52, 'Mops'),
       (53, 'Perser (Mischling)'),
       (54, 'Pitbull Terrier'),
       (55, 'Ratonero Bodeguero Andaluz'),
       (56, 'Schäferhund (Mischling)'),
       (57, 'Yorkshire-Pudel (Mischling)'),
       (58, 'Ziegensittich'),
       (59, 'Kanarienvogel'),
       (60, 'Maine Coon'),
       (61, 'Wellensittich'),
       (62, 'Bullterrier'),
       (63, 'Pinscher'),
       (64, 'Amstaff'),
       (65, 'Kaninchen'),
       (66, 'Kangal Mix'),
       (67, 'Ratonero Bodeguero Andaluz');

INSERT INTO pet_colors(id, name)
VALUES (1, 'Weiß'),
       (2, 'Braun'),
       (3, 'Schwarz'),
       (4, 'Schwarz-weiß'),
       (5, 'Braun-weiß'),
       (6, 'Tricolor'),
       (7, 'Getigert'),
       (8, 'Brauntiger (mit Weiß)'),
       (9, 'Rottiger'),
       (10, 'Schwarz-braun'),
       (11, 'Schwarz-braun-grau'),
       (12, 'Rot'),
       (13, 'Rotbraun'),
       (14, 'Hellbraun'),
       (15, 'Beige-weiß'),
       (16, 'Gelb-braun'),
       (17, 'Blau-grau'),
       (18, 'Grün-gelb'),
       (19, 'Schildpatt'),
       (20, 'Blond'),
       (21, 'Beige'),
       (22, 'Grau'),
       (23, 'Creme'),
       (24, 'Gestromt'),
       (25, 'Silbertiger'),
       (26, 'Weiß-grau'),
       (27, 'Schoko-braun'),
       (28, 'Orange'),
       (29, 'Rot-weiß'),
       (30, 'Schwarz-weiß-grau'),
       (31, 'Schwarz gestromt'),
       (32, 'Braun-meliert'),
       (33, 'Braun-orange'),
       (34, 'Beige-grau'),
       (35, 'Beige-braun'),
       (36, 'Blau'),
       (37, 'Blau-weiß'),
       (38, 'Grün'),
       (39, 'Getigert mit Weiß'),
       (40, 'Brauntiger'),
       (41, 'Gestromt Merle'),
       (42, 'weiß-orange-schwarz'),
       (43, 'braun mit hellen Stellen'),
       (44, 'weiß mit schwarzem Abzeichen'),
       (45, 'grautiger mit weiß'),
       (46, 'Grautiger'),
       (47, 'Gelb'),
       (48, 'Blau');